import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export type ProjectKBConfig = {
  pi_memory_path: string;
  discovered_at: string;
};

// Repo-local .pi-memory is only an ephemeral scratchpad/scaffold. Durable
// knowledge belongs in the Obsidian semantic ontology: wiki/, journal/,
// inbox/, and sources/. Do not create legacy .l2/.l3/.l4 buckets.
const PROJECT_KB_DIRS = [
  "scratchpad/sections",
  "scratchpad/sessions/daily",
] as const;

export function projectKBConfigPath(cwd: string) {
  return path.join(cwd, ".pi", "sherpa.md");
}

export function defaultProjectKBBasedir(cwd: string) {
  return path.join(cwd, ".pi-memory");
}

export function loadProjectKBConfig(cwd: string): ProjectKBConfig | null {
  const configPath = projectKBConfigPath(cwd);
  if (!existsSync(configPath)) return null;

  try {
    const raw = readFileSync(configPath, "utf8");
    const match = raw.match(/pi_memory_path:\s*(.+)/m);
    return {
      pi_memory_path: match ? match[1]!.trim() : defaultProjectKBBasedir(cwd),
      discovered_at: new Date().toISOString(),
    };
  } catch {
    return null;
  }
}

export function ensureProjectKBDirs(kbBase: string) {
  for (const dir of PROJECT_KB_DIRS) {
    mkdirSync(path.join(kbBase, dir), { recursive: true });
  }
  return kbBase;
}

export function ensureProjectKB(cwd: string) {
  const configPath = projectKBConfigPath(cwd);
  const kbBase = defaultProjectKBBasedir(cwd);
  if (existsSync(configPath)) return ensureProjectKBDirs(kbBase);

  mkdirSync(path.join(cwd, ".pi"), { recursive: true });
  ensureProjectKBDirs(kbBase);

  writeFileSync(configPath, [
    "# Sherpa — Project Memory Config",
    "",
    "Auto-generated by Sherpa on first use.",
    "Repo-local .pi-memory is an ephemeral scratchpad scaffold; durable knowledge belongs in Obsidian project memory under the semantic wiki ontology.",
    "",
    "## KB Location",
    `pi_memory_path: ${kbBase}`,
    "",
    "## Routing Overrides",
    "# Add project-specific routing overrides here.",
    "",
    "## Discovered Conventions",
    "# Auto-populated as Sherpa learns project patterns.",
    "",
  ].join("\n"));

  return kbBase;
}

export function getProjectKBBasedir(cwd: string) {
  const config = loadProjectKBConfig(cwd);
  return ensureProjectKBDirs(config ? config.pi_memory_path : ensureProjectKB(cwd));
}
